spring:
  application:
    name: chatDemo
  ai:
    vectorstore:
      pgvector: 768
      initializa-schema: true
    ollama:
      embedding:
        model: nomic-embed-text #размер 768
        base-url: http://localhost:11434
        chat:
          model: gemma3:1b

